### ISSUE TITLE
Modifier keys (Ctrl & Meta)

### ISSUE THREAD

**Issue by W-Bosman** [dessalines/thumb-key#1198]
### Describe your suggested feature

A way of sending modifier keys, especially Ctrl and Meta, would be nice. 

(my usecase is emacs, for which I now have to switch to Unexpected Keyboard.)

Suggested interface: swiping bottom-left (bottom-right) on the numerical '#' key modifies the next key with Ctrl (Meta). 

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have updated the app to **[the latest version](https://github.com/dessalines/thumb-key/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I have searched the existing issues and this is a new one, **NOT** a  duplicate or related to another open issue.
- [X] This is a **single** feature request, in case of multiple feature  requests I will open a separate issue for each one (they can always link to each other if related)
- [X] This is not a question or a discussion, in which case I should have  gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I will fill out all of the requested information in this form.

**Comment by dessalines** [comment]
These are done on programming-specific layouts, not universally.
